
### Get all books
GET http://localhost:3000/books


### Get one book
GET http://localhost:3000/books/64528ff7d31ed336b3d85651




### Create
POST http://localhost:3000/books HTTP/1.1
content-type: application/json

{
    "title": "goosebumbs",
    "author": "Brandon",
    "pages": "300",
    "dateFinished": "12/12/12",
    "read": "true",
    "datePublished": "2000s",
    "genre": "Fantasy"
}


 //Production Deploy


###
GET https://tracker-iio1.onrender.com/books

### Get book by id 

GET https://tracker-iio1.onrender.com/books/64528ff7d31ed336b3d85651

### Create book

POST https://tracker-iio1.onrender.com/books HTTP/1.1
content-type: application/json

{
    "title": "Warbreaker",
    "author": "Brandon",
    "pages": "400",
    "dateFinished": "12/12/12",
    "read": "true",
    "datePublished": "2000s",
    "genre": "Fantasy"
  },







// Users

###Get all users

GET http://localhost:3000/users

###Get single user

GET http://localhost:3000/users/6453315773fca723aca21dd2


### Create User

POST http://localhost:3000/users HTTP/1.1
content-type: application/json

{
    "firstName": "Jorge",
    "lastName": "Gallegos",
    "username": "jorgeG",
    "birthday": "12/12/12",
    "email": "jorge@test.com"
  }


  // Production Deploy

###

GET https://tracker-iio1.onrender.com/users

### get user by id

GET https://tracker-iio1.onrender.com/users/6453315773fca723aca21dd2

### create user
POST https://tracker-iio1.onrender.com/users HTTP/1.1
content-type: application/json

{
    "firstName": "veronica",
    "lastName": "Gallegos",
    "username": "jorgeG",
    "birthday": "12/12/12",
    "email": "jorge@test.com"
  }