
### Get all books
GET http://localhost:3000/books


### Get one book
GET http://localhost:3000/books/64528ff7d31ed336b3d85651



### Create book

POST http://localhost:3000/books HTTP/1.1
content-type: application/json
{
    "title": "Warbreaker",
    "author": "Brandon",
    "pages": "300",
    "dateFinished": "12/12/12",
    "read": "true",
    "datePublished": "2000s",
    "genre": "Fantasy"
  },


  