
### Get all books
GET http://localhost:3000/books


### Get one book
GET http://localhost:3000/books/64528ff7d31ed336b3d85651




### Create
POST http://localhost:3000/books HTTP/1.1
content-type: application/json

{
    "title": "goosebumbs",
    "author": "Brandon",
    "pages": "300",
    "dateFinished": "12/12/12",
    "read": "true",
    "datePublished": "2000s",
    "genre": "Fantasy"
}


### PUT contact 
PUT http://localhost:3000/books/64528ff7d31ed336b3d85653 HTTP/1.1
content-type: application/json

{"_id":"64528ff7d31ed336b3d85653","title":"any","author":"any","pages":"any","dateFinished":"any","read":"any","datePublished":"2016","genre":"any"},

### DELETE contact 
DELETE http://localhost:3000/contacts/645348be9bc6ab7274467d71 HTTP/1.1



 //Production Deploy


###
GET https://tracker-iio1.onrender.com/books

### Get book by id 

GET https://tracker-iio1.onrender.com/books/64528ff7d31ed336b3d85651

### Create book

POST https://tracker-iio1.onrender.com/books HTTP/1.1
content-type: application/json

{
    "title": "Warbreaker",
    "author": "Brandon",
    "pages": "400",
    "dateFinished": "12/12/12",
    "read": "true",
    "datePublished": "2000s",
    "genre": "Fantasy"
  },


### update book

PUT https://tracker-iio1.onrender.com/books/64528ff7d31ed336b3d85653 HTTP/1.1
content-type: application/json

{"_id":"64528ff7d31ed336b3d85653","title":"any","author":"any","pages":"any","dateFinished":"any","read":"any",
"datePublished":"2016","genre":"any"},

### delete book

DELETE https://tracker-iio1.onrender.com/books/645343519c3403bb84edb177 HTTP/1.1











// Users

###Get all users

GET http://localhost:3000/users

###Get single user

GET http://localhost:3000/users/6453315773fca723aca21dd2


### Create User

POST http://localhost:3000/users HTTP/1.1
content-type: application/json

{
    "firstName": "Jorge",
    "lastName": "Gallegos",
    "username": "jorgeG",
    "birthday": "12/12/12",
    "email": "jorge@test.com"
  }

### update

PUT http://localhost:3000/users/6453315773fca723aca21dd4 HTTP/1.1
content-type: application/json

{
    "firstName": "Jorge",
    "lastName": "Gallegos",
    "username": "jorgeG",
    "birthday": "12/12/12",
    "email": "jorge@test.com"
  }

### delete
DELETE http://localhost:3000/users/6453315773fca723aca21dd2





  // Production Deploy

###

GET https://tracker-iio1.onrender.com/users

### get user by id

GET https://tracker-iio1.onrender.com/users/6453315773fca723aca21dd2

### create user
POST https://tracker-iio1.onrender.com/users HTTP/1.1
content-type: application/json

{
    "firstName": "veronica",
    "lastName": "Gallegos",
    "username": "jorgeG",
    "birthday": "12/12/12",
    "email": "jorge@test.com"
  }

### update

PUT https://tracker-iio1.onrender.com/users/6453315773fca723aca21dd2 HTTP/1.1
content-type: application/json

{"_id":"6453315773fca723aca21dd2",
"firstName":"Camila",
"lastName":"Gallegos","username":"camigm1","birthday":"12/12/12","email":"camigm1@test.com"}


### delete

DELETE https://tracker-iio1.onrender.com/users/6453315773fca723aca21dd3